### ISSUE TITLE
Warning: Please change before next release: cordova-plugin-music-controls -> cordova-plugin-music-controls2

### ISSUE THREAD

**Issue by Neustradamus** [Xtraball/Siberian#760]
@Xtraball, @Slicit: We can read on https://github.com/homerours/cordova-music-controls-plugin/blob/master/README.md:
`Gavin Henry (ghenry22) has been maintaining a fork that should be updated and working better than this one. Please use his fork.`
- https://github.com/ghenry22/cordova-plugin-music-controls2

Currently 3.0.5: https://github.com/ghenry22/cordova-plugin-music-controls2/releases

**Comment by SiberianCMS** [comment]
@Neustradamus it's already the case, all our modules are curated before every native update, and we ensure to have the latest when required

https://github.com/Xtraball/MusicControls/tree/siberian

(it's still a fork from https://github.com/homerours/cordova-music-controls-plugin) but music-controls-2 have been back-merged and ..... fixed too (because hell, it's not even working correctly ...)

**Comment by Neustradamus** [comment]
@SiberianCMS: Thanks for your reply!

I think it is better to fork https://github.com/ghenry22/cordova-plugin-music-controls2 and not https://github.com/homerours/cordova-music-controls-plugin.

**Comment by SiberianCMS** [comment]
@Neustradamus we can't change the origin fork, so for now, it will stay like this.

Anyway, these cordova plugins are goign to be part of our "Curated cordova plugin"

There was so much work done to make them working all with each other they deserve to be known :D
