### ISSUE TITLE
{ "error": true, "message": "session has already been started by session.auto-start or session_start()" }

### ISSUE THREAD

**Issue by AnythingLinux** [Xtraball/Siberian#806]
I am using Ubuntu 20.04. After setup Siberian and when i visit ip address it shows { "error": true, "message": "session has already been started by session.auto-start or session_start()" }

any one face this problem and know how to fix it?

**Comment by SiberianCMS** [comment]
When this kind of error happens, it's most probably due to a php error or something like, which outputs buffer before any session, please check you have correctly installed Siberian with all the correct permissions

The first thing I see, and which can cause this, is the var/ folder (and var/log, var/cache, var/tmp) not writeable, causing issues with logs, causing session unable to start.

**Comment by SiberianCMS** [comment]
Close as stalled, not relevant anymore
